#ifndef BONUSWORKTRIAL_SELECTIONSORTALGORITHM_H
#define BONUSWORKTRIAL_SELECTIONSORTALGORITHM_H

class SelectionSortAlgorithm {
public:
    void SelectionSort(int A[], int n);
};

#endif //BONUSWORKTRIAL_SELECTIONSORTALGORITHM_H
