#ifndef BONUSWORKTRIAL_SEARCHELEMENTINACIRCULARSORTEDARRAY_H
#define BONUSWORKTRIAL_SEARCHELEMENTINACIRCULARSORTEDARRAY_H

class SearchElementInACircularSortedArray {
public:
    int CircularArraySearch(int A[],int n, int x);
};

#endif //BONUSWORKTRIAL_SEARCHELEMENTINACIRCULARSORTEDARRAY_H
