#ifndef BONUSWORKTRIAL_HOWMANYTIMESISASORTEDARRAYROTATED_H
#define BONUSWORKTRIAL_HOWMANYTIMESISASORTEDARRAYROTATED_H

class HowManyTimesIsASortedArrayRotated {
public:
    int FindRotationCount(int A[],int n);
};

#endif //BONUSWORKTRIAL_HOWMANYTIMESISASORTEDARRAYROTATED_H
